/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mvwqvqtjj5d4vobxqmhjfjacm4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bqm7jc6scjh3bceryykf6qehpq",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://z6uve5zctl.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:1199f837-f402-4860-ab4f-dfb06ed8e5f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VfqL3yvuW",
    "aws_user_pools_web_client_id": "1am5d8aj384g3u0iv75tam1vmj",
    "oauth": {
        "domain": "fabulous10nails-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://main.ds1uw7j2jr6ye.amplifyapp.com/",
        "redirectSignOut": "https://main.ds1uw7j2jr6ye.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "fabulous10nails70e6e2e779134ec68b7856ab5c4db20a8c2d4-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
